spring:
  application:
    name: config-test
#Eureka config
eureka:
  instance:
    prefer-ip-address: true
  client:
    # by default true learning purpose make it configured
    # register-with-eureka: true
    # fetch-registory: true
    register-with-eureka: true
    fetch-registory: true
    service-url:
      defaultZone: http://localhost:8761/eureka
